"""up

Revision ID: 0e2bbbbbc22d
Revises: 8a2d97241e68
Create Date: 2025-05-19 13:42:59.121949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2bbbbbc22d'
down_revision: Union[str, None] = '8a2d97241e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('client_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'messages', ['client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_column('messages', 'client_id')
    # ### end Alembic commands ###
