"""up

Revision ID: 13260ed6cab0
Revises: a23b86a24978
Create Date: 2025-05-19 23:49:43.278479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13260ed6cab0'
down_revision: Union[str, None] = 'a23b86a24978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user1_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('user2_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['user2_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['user1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user2_id')
    op.drop_column('chats', 'user1_id')
    # ### end Alembic commands ###
