"""up

Revision ID: a26b07ef0f6f
Revises: 13260ed6cab0
Create Date: 2025-05-20 20:39:56.639009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26b07ef0f6f'
down_revision: Union[str, None] = '13260ed6cab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'groups', 'chats', ['id'], ['id'])
    op.add_column('messages', sa.Column('read_by', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read_by')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    # ### end Alembic commands ###
